services:
  nginx:
    image: nginx:latest
    ports:
      # - 80:80
      - 8443:443
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/ssl:/etc/ssl
      - ./html:/usr/share/nginx/html
